// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $atoms_badge from "./routes/atoms/badge.tsx";
import * as $atoms_blockquote from "./routes/atoms/blockquote.tsx";
import * as $atoms_button from "./routes/atoms/button.tsx";
import * as $atoms_checkbox from "./routes/atoms/checkbox.tsx";
import * as $atoms_code_block from "./routes/atoms/code-block.tsx";
import * as $atoms_h1 from "./routes/atoms/h1.tsx";
import * as $atoms_h2 from "./routes/atoms/h2.tsx";
import * as $atoms_highlight from "./routes/atoms/highlight.tsx";
import * as $atoms_inline_code from "./routes/atoms/inline-code.tsx";
import * as $atoms_input from "./routes/atoms/input.tsx";
import * as $atoms_link from "./routes/atoms/link.tsx";
import * as $atoms_ol from "./routes/atoms/ol.tsx";
import * as $atoms_radio_button from "./routes/atoms/radio-button.tsx";
import * as $atoms_select from "./routes/atoms/select.tsx";
import * as $atoms_table from "./routes/atoms/table.tsx";
import * as $atoms_text from "./routes/atoms/text.tsx";
import * as $atoms_textarea from "./routes/atoms/textarea.tsx";
import * as $atoms_ul from "./routes/atoms/ul.tsx";
import * as $faq from "./routes/faq.tsx";
import * as $getting_started from "./routes/getting-started.tsx";
import * as $helpers_container from "./routes/helpers/container.tsx";
import * as $helpers_flex from "./routes/helpers/flex.tsx";
import * as $helpers_stack from "./routes/helpers/stack.tsx";
import * as $index from "./routes/index.tsx";
import * as $molecules_alert from "./routes/molecules/alert.tsx";
import * as $molecules_card from "./routes/molecules/card.tsx";
import * as $molecules_footer from "./routes/molecules/footer.tsx";
import * as $molecules_form_field from "./routes/molecules/form-field.tsx";
import * as $molecules_navbar from "./routes/molecules/navbar.tsx";
import * as $molecules_password_input from "./routes/molecules/password-input.tsx";
import * as $molecules_stepper from "./routes/molecules/stepper.tsx";
import * as $philosophy from "./routes/philosophy.tsx";
import * as $demo_example from "./islands/demo/example.tsx";
import * as $demo_examples from "./islands/demo/examples.tsx";
import * as $molecules_alert_1 from "./islands/molecules/alert.tsx";
import * as $molecules_password_input_1 from "./islands/molecules/password-input.tsx";
import * as $molecules_stepper_1 from "./islands/molecules/stepper.tsx";
import * as $welcome_message from "./islands/welcome-message.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/atoms/badge.tsx": $atoms_badge,
    "./routes/atoms/blockquote.tsx": $atoms_blockquote,
    "./routes/atoms/button.tsx": $atoms_button,
    "./routes/atoms/checkbox.tsx": $atoms_checkbox,
    "./routes/atoms/code-block.tsx": $atoms_code_block,
    "./routes/atoms/h1.tsx": $atoms_h1,
    "./routes/atoms/h2.tsx": $atoms_h2,
    "./routes/atoms/highlight.tsx": $atoms_highlight,
    "./routes/atoms/inline-code.tsx": $atoms_inline_code,
    "./routes/atoms/input.tsx": $atoms_input,
    "./routes/atoms/link.tsx": $atoms_link,
    "./routes/atoms/ol.tsx": $atoms_ol,
    "./routes/atoms/radio-button.tsx": $atoms_radio_button,
    "./routes/atoms/select.tsx": $atoms_select,
    "./routes/atoms/table.tsx": $atoms_table,
    "./routes/atoms/text.tsx": $atoms_text,
    "./routes/atoms/textarea.tsx": $atoms_textarea,
    "./routes/atoms/ul.tsx": $atoms_ul,
    "./routes/faq.tsx": $faq,
    "./routes/getting-started.tsx": $getting_started,
    "./routes/helpers/container.tsx": $helpers_container,
    "./routes/helpers/flex.tsx": $helpers_flex,
    "./routes/helpers/stack.tsx": $helpers_stack,
    "./routes/index.tsx": $index,
    "./routes/molecules/alert.tsx": $molecules_alert,
    "./routes/molecules/card.tsx": $molecules_card,
    "./routes/molecules/footer.tsx": $molecules_footer,
    "./routes/molecules/form-field.tsx": $molecules_form_field,
    "./routes/molecules/navbar.tsx": $molecules_navbar,
    "./routes/molecules/password-input.tsx": $molecules_password_input,
    "./routes/molecules/stepper.tsx": $molecules_stepper,
    "./routes/philosophy.tsx": $philosophy,
  },
  islands: {
    "./islands/demo/example.tsx": $demo_example,
    "./islands/demo/examples.tsx": $demo_examples,
    "./islands/molecules/alert.tsx": $molecules_alert_1,
    "./islands/molecules/password-input.tsx": $molecules_password_input_1,
    "./islands/molecules/stepper.tsx": $molecules_stepper_1,
    "./islands/welcome-message.tsx": $welcome_message,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
