// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/atoms/badge.tsx";
import * as $4 from "./routes/atoms/button.tsx";
import * as $5 from "./routes/atoms/link.tsx";
import * as $6 from "./routes/atoms/new-tab-icon.tsx";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/demo/example.tsx";
import * as $$1 from "./islands/demo/examples.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/atoms/badge.tsx": $3,
    "./routes/atoms/button.tsx": $4,
    "./routes/atoms/link.tsx": $5,
    "./routes/atoms/new-tab-icon.tsx": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/demo/example.tsx": $$0,
    "./islands/demo/examples.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
