export default {
  content: [
    "{islands,components}/**/*.{ts,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: "var(--fontFamily-sans)",
    },
    colors: {
      primary: {
        50: "rgb(var(--color-primary-50) / <alpha-value>)",
        100: "rgb(var(--color-primary-100) / <alpha-value>)",
        200: "rgb(var(--color-primary-200) / <alpha-value>)",
        300: "rgb(var(--color-primary-300) / <alpha-value>)",
        400: "rgb(var(--color-primary-400) / <alpha-value>)",
        500: "rgb(var(--color-primary-500) / <alpha-value>)",
        600: "rgb(var(--color-primary-600) / <alpha-value>)",
        700: "rgb(var(--color-primary-700) / <alpha-value>)",
        800: "rgb(var(--color-primary-800) / <alpha-value>)",
        900: "rgb(var(--color-primary-900) / <alpha-value>)",
      },
      neutral: {
        50: "rgb(var(--color-neutral-50) / <alpha-value>)",
        100: "rgb(var(--color-neutral-100) / <alpha-value>)",
        200: "rgb(var(--color-neutral-200) / <alpha-value>)",
        300: "rgb(var(--color-neutral-300) / <alpha-value>)",
        400: "rgb(var(--color-neutral-400) / <alpha-value>)",
        500: "rgb(var(--color-neutral-500) / <alpha-value>)",
        600: "rgb(var(--color-neutral-600) / <alpha-value>)",
        700: "rgb(var(--color-neutral-700) / <alpha-value>)",
        800: "rgb(var(--color-neutral-800) / <alpha-value>)",
        900: "rgb(var(--color-neutral-900) / <alpha-value>)",
      },
      supporting: {
        green: {
          50: "rgb(var(--color-supporting-green-50) / <alpha-value>)",
          100: "rgb(var(--color-supporting-green-100) / <alpha-value>)",
          200: "rgb(var(--color-supporting-green-200) / <alpha-value>)",
          300: "rgb(var(--color-supporting-green-300) / <alpha-value>)",
          400: "rgb(var(--color-supporting-green-400) / <alpha-value>)",
          500: "rgb(var(--color-supporting-green-500) / <alpha-value>)",
          600: "rgb(var(--color-supporting-green-600) / <alpha-value>)",
          700: "rgb(var(--color-supporting-green-700) / <alpha-value>)",
          800: "rgb(var(--color-supporting-green-800) / <alpha-value>)",
          900: "rgb(var(--color-supporting-green-900) / <alpha-value>)",
        },
        yellow: {
          50: "rgb(var(--color-supporting-yellow-50) / <alpha-value>)",
          100: "rgb(var(--color-supporting-yellow-100) / <alpha-value>)",
          200: "rgb(var(--color-supporting-yellow-200) / <alpha-value>)",
          300: "rgb(var(--color-supporting-yellow-300) / <alpha-value>)",
          400: "rgb(var(--color-supporting-yellow-400) / <alpha-value>)",
          500: "rgb(var(--color-supporting-yellow-500) / <alpha-value>)",
          600: "rgb(var(--color-supporting-yellow-600) / <alpha-value>)",
          700: "rgb(var(--color-supporting-yellow-700) / <alpha-value>)",
          800: "rgb(var(--color-supporting-yellow-800) / <alpha-value>)",
          900: "rgb(var(--color-supporting-yellow-900) / <alpha-value>)",
        },
        cyan: {
          50: "rgb(var(--color-supporting-cyan-50) / <alpha-value>)",
          100: "rgb(var(--color-supporting-cyan-100) / <alpha-value>)",
          200: "rgb(var(--color-supporting-cyan-200) / <alpha-value>)",
          300: "rgb(var(--color-supporting-cyan-300) / <alpha-value>)",
          400: "rgb(var(--color-supporting-cyan-400) / <alpha-value>)",
          500: "rgb(var(--color-supporting-cyan-500) / <alpha-value>)",
          600: "rgb(var(--color-supporting-cyan-600) / <alpha-value>)",
          700: "rgb(var(--color-supporting-cyan-700) / <alpha-value>)",
          800: "rgb(var(--color-supporting-cyan-800) / <alpha-value>)",
          900: "rgb(var(--color-supporting-cyan-900) / <alpha-value>)",
        },
        red: {
          50: "rgb(var(--color-supporting-red-50) / <alpha-value>)",
          100: "rgb(var(--color-supporting-red-100) / <alpha-value>)",
          200: "rgb(var(--color-supporting-red-200) / <alpha-value>)",
          300: "rgb(var(--color-supporting-red-300) / <alpha-value>)",
          400: "rgb(var(--color-supporting-red-400) / <alpha-value>)",
          500: "rgb(var(--color-supporting-red-500) / <alpha-value>)",
          600: "rgb(var(--color-supporting-red-600) / <alpha-value>)",
          700: "rgb(var(--color-supporting-red-700) / <alpha-value>)",
          800: "rgb(var(--color-supporting-red-800) / <alpha-value>)",
          900: "rgb(var(--color-supporting-red-900) / <alpha-value>)",
        },
      },
    },
    extend: {
      spacing: {
        px: "var(--spacing-px)",
        0: "var(--spacing-0)",
        1: "var(--spacing-1)",
        2: "var(--spacing-2)",
        3: "var(--spacing-3)",
        4: "var(--spacing-4)",
        5: "var(--spacing-5)",
        6: "var(--spacing-6)",
        7: "var(--spacing-7)",
        8: "var(--spacing-8)",
        9: "var(--spacing-9)",
        10: "var(--spacing-10)",
        11: "var(--spacing-11)",
        12: "var(--spacing-12)",
        13: "var(--spacing-13)",
        14: "var(--spacing-14)",
        15: "var(--spacing-15)",
        16: "var(--spacing-16)",
      },
    },
  },
} as const;
